#!/bin/bash

set -e

DIR="$( cd "$(dirname "$( dirname "${BASH_SOURCE[0]}" )" )" && pwd )"
TMPDIR="$( mktemp -d )"

confirm() {
  # call with a prompt string or use a default
  read -r -p "${1:-Are you sure? [y/N]} " response
  case "$response" in
    [yY][eE][sS]|[yY])
      true
      ;;
    *)
      false
      ;;
  esac
}

trap 'cleanup' INT TERM EXIT
cleanup () {
  [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"
  kill $SERVER_PID
}

$DIR/tools/gen $TMPDIR
$DIR/deps/ninja/ninja -C $TMPDIR

cd $TMPDIR/site
python3 -m http.server 7543 &> /dev/null &
SERVER_PID=$!

echo 'Serving on http://localhost:7543'

gsutil -m rsync -r -n -c -d $TMPDIR/site gs://crunch.tsundoku.io/
confirm "Upload?" && gsutil -m rsync -r -c -d $TMPDIR/site gs://crunch.tsundoku.io/
confirm "Publish?" && npm publish --access public $TMPDIR/crunch/

