#!/bin/bash
set -e

ROOT="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" && pwd )"
OUT=out

# $ROOT/deps/node/bin/node --experimental-modules $OUT/crunch/run_systemtests.mjs
# $ROOT/deps/node/bin/node $OUT/crunch/run_systemtests.js

(
cd $OUT/tests/rollup_simple
rm -f cjs_bundle.js umd_bundle.js
$ROOT/deps/node/bin/npm ci
$ROOT/deps/node/bin/node node_modules/.bin/rollup -c cjs_rollup.config.js
$ROOT/deps/node/bin/node node_modules/.bin/rollup -c umd_rollup.config.js
$ROOT/deps/node/bin/node cjs_bundle.js
$ROOT/deps/node/bin/node umd_bundle.js
)

